//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_BusinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIt02_archivoEstudioCompl
    {
        public long idArchivoEstudioCompl { get; set; }
        public string descArchivoEstudioCompl { get; set; }
        public string pathArchivo { get; set; }
        public long idEstudioCompl { get; set; }
    
        public virtual CLlt10_estudioCompl CLlt10_estudioCompl { get; set; }
    }
}
