//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_BusinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLlt16_tratamiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLlt16_tratamiento()
        {
            this.CLlt17_tratamientoDtl = new HashSet<CLlt17_tratamientoDtl>();
            oListTratamientoDtl = new List<CLlt17_tratamientoDtl>();
        }
    
        public long idTratamiento { get; set; }
        public string descTratamiento { get; set; }
        public Nullable<long> idDiagnostico { get; set; }

        public List<CLlt17_tratamientoDtl> oListTratamientoDtl { get; set; }

        public virtual CLlt08_diagnostico CLlt08_diagnostico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLlt17_tratamientoDtl> CLlt17_tratamientoDtl { get; set; }
    }
}
