//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_BusinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLlt17_tratamientoDtl
    {
        public long idTratamientoDtl { get; set; }
        public bool esServicio { get; set; }
        public string indicacionServicio { get; set; }
        public long idTratamiento { get; set; }
        public long idProducto { get; set; }
        public long idServicio { get; set; }
    
        public virtual CLlt16_tratamiento CLlt16_tratamiento { get; set; }
        public virtual PROt02_producto PROt02_producto { get; set; }
        public virtual PROt04_servicio PROt04_servicio { get; set; }
    }
}
