//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_BusinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLlt08_diagnostico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLlt08_diagnostico()
        {
            this.CLlt16_tratamiento = new HashSet<CLlt16_tratamiento>();
        }
    
        public long idDiagnostico { get; set; }
        public string descDiagnostico { get; set; }
        public long idAtencion { get; set; }
        public Nullable<int> idCie10 { get; set; }
    
        public virtual CLlt03_atencion CLlt03_atencion { get; set; }
        public virtual CLlt04_cie10 CLlt04_cie10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLlt16_tratamiento> CLlt16_tratamiento { get; set; }
    }
}
