//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_BusinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLlt11_evolucion
    {
        public long idEvolucion { get; set; }
        public string descEvolucion { get; set; }
        public Nullable<bool> pesimo { get; set; }
        public Nullable<bool> malo { get; set; }
        public Nullable<bool> regular { get; set; }
        public Nullable<bool> bueno { get; set; }
        public Nullable<bool> excelente { get; set; }
        public long idAtencion { get; set; }
    
        public virtual CLlt03_atencion CLlt03_atencion { get; set; }
    }
}
