//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_BusinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLlt13_funcionVital
    {
        public long idFuncionVital { get; set; }
        public string sistole { get; set; }
        public string diastole { get; set; }
        public string pulsacion { get; set; }
        public string ritmoRespiratorio { get; set; }
        public string temperatura { get; set; }
        public string altura { get; set; }
        public string peso { get; set; }
        public string imc { get; set; }
        public long idAtencion { get; set; }
    
        public virtual CLlt03_atencion CLlt03_atencion { get; set; }
    }
}
