//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_BusinessEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Asiri_ERPEntities : DbContext
    {
        public Asiri_ERPEntities()
            : base("name=Asiri_ERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIt01_anamnesis> CLIt01_anamnesis { get; set; }
        public virtual DbSet<CLIt02_archivoEstudioCompl> CLIt02_archivoEstudioCompl { get; set; }
        public virtual DbSet<CLlt03_atencion> CLlt03_atencion { get; set; }
        public virtual DbSet<CLlt04_cie10> CLlt04_cie10 { get; set; }
        public virtual DbSet<CLlt05_cita> CLlt05_cita { get; set; }
        public virtual DbSet<CLlt06_citaDtl> CLlt06_citaDtl { get; set; }
        public virtual DbSet<CLlt07_consultorio> CLlt07_consultorio { get; set; }
        public virtual DbSet<CLlt08_diagnostico> CLlt08_diagnostico { get; set; }
        public virtual DbSet<CLlt09_estadoCita> CLlt09_estadoCita { get; set; }
        public virtual DbSet<CLlt10_estudioCompl> CLlt10_estudioCompl { get; set; }
        public virtual DbSet<CLlt11_evolucion> CLlt11_evolucion { get; set; }
        public virtual DbSet<CLlt12_examenFisico> CLlt12_examenFisico { get; set; }
        public virtual DbSet<CLlt13_funcionVital> CLlt13_funcionVital { get; set; }
        public virtual DbSet<CLlt14_seguro> CLlt14_seguro { get; set; }
        public virtual DbSet<CLlt15_seguroPaciente> CLlt15_seguroPaciente { get; set; }
        public virtual DbSet<CLlt16_tratamiento> CLlt16_tratamiento { get; set; }
        public virtual DbSet<CLlt17_tratamientoDtl> CLlt17_tratamientoDtl { get; set; }
        public virtual DbSet<MSTt01_medioDePago> MSTt01_medioDePago { get; set; }
        public virtual DbSet<MSTt02_piso> MSTt02_piso { get; set; }
        public virtual DbSet<MSTt03_redSocial> MSTt03_redSocial { get; set; }
        public virtual DbSet<MSTt04_sucursal> MSTt04_sucursal { get; set; }
        public virtual DbSet<MSTt05_tipoSucursal> MSTt05_tipoSucursal { get; set; }
        public virtual DbSet<PROt01_categoria> PROt01_categoria { get; set; }
        public virtual DbSet<PROt02_producto> PROt02_producto { get; set; }
        public virtual DbSet<PROt03_productoUnidadDeMedida> PROt03_productoUnidadDeMedida { get; set; }
        public virtual DbSet<PROt04_servicio> PROt04_servicio { get; set; }
        public virtual DbSet<PROt05_tipoDeServicio> PROt05_tipoDeServicio { get; set; }
        public virtual DbSet<PROt06_unidadDeMedida> PROt06_unidadDeMedida { get; set; }
        public virtual DbSet<RHUt01_empleado> RHUt01_empleado { get; set; }
        public virtual DbSet<RHUt02_empleadoEspecialidad> RHUt02_empleadoEspecialidad { get; set; }
        public virtual DbSet<RHUt03_empleadoTurno> RHUt03_empleadoTurno { get; set; }
        public virtual DbSet<RHUt04_especialidad> RHUt04_especialidad { get; set; }
        public virtual DbSet<RHUt05_estadoCivil> RHUt05_estadoCivil { get; set; }
        public virtual DbSet<RHUt06_horario> RHUt06_horario { get; set; }
        public virtual DbSet<RHUt07_paciente> RHUt07_paciente { get; set; }
        public virtual DbSet<RHUt08_periodoRemuneracion> RHUt08_periodoRemuneracion { get; set; }
        public virtual DbSet<RHUt09_persona> RHUt09_persona { get; set; }
        public virtual DbSet<RHUt10_personaRedSocial> RHUt10_personaRedSocial { get; set; }
        public virtual DbSet<RHUt11_tipoDeEmpleado> RHUt11_tipoDeEmpleado { get; set; }
        public virtual DbSet<RHUt12_tipoDocIdentidad> RHUt12_tipoDocIdentidad { get; set; }
        public virtual DbSet<RHUt13_tipoEspecialidad> RHUt13_tipoEspecialidad { get; set; }
        public virtual DbSet<RHUt14_turno> RHUt14_turno { get; set; }
        public virtual DbSet<SISt01_parametro> SISt01_parametro { get; set; }
        public virtual DbSet<SNTt01_entidadFinanciera> SNTt01_entidadFinanciera { get; set; }
        public virtual DbSet<SNTt02_impuesto> SNTt02_impuesto { get; set; }
        public virtual DbSet<SNTt03_moneda> SNTt03_moneda { get; set; }
        public virtual DbSet<SNTt04_tipoComprobante> SNTt04_tipoComprobante { get; set; }
        public virtual DbSet<SNTt05_tipoMedioDePago> SNTt05_tipoMedioDePago { get; set; }
        public virtual DbSet<TNSt01_comprobanteEmitido> TNSt01_comprobanteEmitido { get; set; }
        public virtual DbSet<TNSt02_comprobanteEmitidoDtl> TNSt02_comprobanteEmitidoDtl { get; set; }
        public virtual DbSet<TNSt03_cuota> TNSt03_cuota { get; set; }
        public virtual DbSet<TNSt04_estadoComprobante> TNSt04_estadoComprobante { get; set; }
        public virtual DbSet<TNSt05_estadoDeCuenta> TNSt05_estadoDeCuenta { get; set; }
        public virtual DbSet<TNSt06_medioDePagoDtl> TNSt06_medioDePagoDtl { get; set; }
        public virtual DbSet<UBIt01_distrito> UBIt01_distrito { get; set; }
        public virtual DbSet<UBIt02_provincia> UBIt02_provincia { get; set; }
        public virtual DbSet<UBIt03_region> UBIt03_region { get; set; }
        public virtual DbSet<UBIt04_via> UBIt04_via { get; set; }
        public virtual DbSet<UBIt05_zona> UBIt05_zona { get; set; }
        public virtual DbSet<USRt01_login> USRt01_login { get; set; }
        public virtual DbSet<USRt02_permiso> USRt02_permiso { get; set; }
        public virtual DbSet<USRt03_rol> USRt03_rol { get; set; }
        public virtual DbSet<USRt04_usuario> USRt04_usuario { get; set; }
        public virtual DbSet<USRt05_usuarioRol> USRt05_usuarioRol { get; set; }
    }
}
