//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_BusinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROt02_producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROt02_producto()
        {
            this.CLlt17_tratamientoDtl = new HashSet<CLlt17_tratamientoDtl>();
            this.PROt03_productoUnidadDeMedida = new HashSet<PROt03_productoUnidadDeMedida>();
        }
    
        public long idProducto { get; set; }
        public string codProducto { get; set; }
        public string codBarra { get; set; }
        public string nombreProductoGenerico { get; set; }
        public string nombreProductoComercial { get; set; }
        public string descProducto { get; set; }
        public string obsvProducto { get; set; }
        public bool activo { get; set; }
        public System.DateTime fecRegistro { get; set; }
        public Nullable<System.DateTime> fecModificacion { get; set; }
        public Nullable<System.DateTime> fecEliminacion { get; set; }
        public long idUsuario { get; set; }
        public Nullable<long> idUsuarioModificar { get; set; }
        public Nullable<long> idUsuarioEliminar { get; set; }
        public int idCategoria { get; set; }
        public int idMoneda { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLlt17_tratamientoDtl> CLlt17_tratamientoDtl { get; set; }
        public virtual PROt01_categoria PROt01_categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROt03_productoUnidadDeMedida> PROt03_productoUnidadDeMedida { get; set; }
        public virtual SNTt03_moneda SNTt03_moneda { get; set; }
    }
}
