//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_BusinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROt03_productoUnidadDeMedida
    {
        public int idUnidadDeMedida { get; set; }
        public long idProducto { get; set; }
        public decimal precio { get; set; }
        public Nullable<decimal> precioMinimo { get; set; }
        public Nullable<decimal> precioMaximo { get; set; }
        public bool activo { get; set; }
        public System.DateTime fecRegistro { get; set; }
        public Nullable<System.DateTime> fecModificacion { get; set; }
        public Nullable<System.DateTime> fecEliminacion { get; set; }
        public long idUsuario { get; set; }
        public Nullable<long> idUsuarioModificar { get; set; }
        public Nullable<long> idUsuarioEliminar { get; set; }
    
        public virtual PROt02_producto PROt02_producto { get; set; }
        public virtual PROt06_unidadDeMedida PROt06_unidadDeMedida { get; set; }
    }
}
