//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_BusinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROt06_unidadDeMedida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROt06_unidadDeMedida()
        {
            this.PROt03_productoUnidadDeMedida = new HashSet<PROt03_productoUnidadDeMedida>();
        }
    
        public int idUnidadDeMedida { get; set; }
        public string codUnidadDeMedida { get; set; }
        public string descUnidadDeMedida { get; set; }
        public bool activo { get; set; }
        public Nullable<System.DateTime> fecRegistro { get; set; }
        public Nullable<System.DateTime> fecModificacion { get; set; }
        public Nullable<System.DateTime> fecEliminacion { get; set; }
        public long idUsuario { get; set; }
        public Nullable<long> idUsuarioModificar { get; set; }
        public Nullable<long> idUsuarioEliminar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROt03_productoUnidadDeMedida> PROt03_productoUnidadDeMedida { get; set; }
    }
}
