//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_BusinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RHUt01_empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RHUt01_empleado()
        {
            this.CLlt05_cita = new HashSet<CLlt05_cita>();
            this.USRt04_usuario = new HashSet<USRt04_usuario>();
            this.RHUt02_empleadoEspecialidad = new HashSet<RHUt02_empleadoEspecialidad>();
            this.RHUt03_empleadoTurno = new HashSet<RHUt03_empleadoTurno>();
            this.RHUt06_horario = new HashSet<RHUt06_horario>();
        }
    
        public long idEmpleado { get; set; }
        public string codEmpleado { get; set; }
        public System.DateTime fecRegistro { get; set; }
        public Nullable<System.DateTime> fecModificacion { get; set; }
        public Nullable<System.DateTime> fecEliminacion { get; set; }
        public Nullable<System.DateTime> fecIngreso { get; set; }
        public Nullable<System.DateTime> fecCese { get; set; }
        public string horasPorPeriodo { get; set; }
        public Nullable<decimal> mtoRemuneracion { get; set; }
        public bool esHorarioTurno { get; set; }
        public string info01 { get; set; }
        public string info02 { get; set; }
        public string info03 { get; set; }
        public string obsvEmpleado { get; set; }
        public bool activo { get; set; }
        public long idUsuario { get; set; }
        public Nullable<long> idUsuarioModificar { get; set; }
        public Nullable<long> idUsuarioEliminar { get; set; }
        public int idEntidadFinanciera { get; set; }
        public int idTipoDeEmpleado { get; set; }
        public Nullable<long> idPersona { get; set; }
        public long idPeriodoRemuneracion { get; set; }
        public short idMedioDePago { get; set; }
        public short idConsultorio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLlt05_cita> CLlt05_cita { get; set; }
        public virtual CLlt07_consultorio CLlt07_consultorio { get; set; }
        public virtual MSTt01_medioDePago MSTt01_medioDePago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USRt04_usuario> USRt04_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RHUt02_empleadoEspecialidad> RHUt02_empleadoEspecialidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RHUt03_empleadoTurno> RHUt03_empleadoTurno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RHUt06_horario> RHUt06_horario { get; set; }
        public virtual RHUt08_periodoRemuneracion RHUt08_periodoRemuneracion { get; set; }
        public virtual RHUt09_persona RHUt09_persona { get; set; }
        public virtual RHUt11_tipoDeEmpleado RHUt11_tipoDeEmpleado { get; set; }
        public virtual SNTt01_entidadFinanciera SNTt01_entidadFinanciera { get; set; }
    }
}
