//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_BusinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SISt01_parametro
    {
        public int idParametro { get; set; }
        public string codParametro { get; set; }
        public string nombreParametro { get; set; }
        public string descParametro { get; set; }
        public string valorDeTexto { get; set; }
        public Nullable<decimal> valorNumerico { get; set; }
        public string valorTextoDefault { get; set; }
        public Nullable<decimal> valorNumericoDefault { get; set; }
        public Nullable<System.DateTime> fecRegistro { get; set; }
        public Nullable<long> idUsuarioModificar { get; set; }
    }
}
