//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_BusinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNSt05_estadoDeCuenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TNSt05_estadoDeCuenta()
        {
            this.TNSt03_cuota = new HashSet<TNSt03_cuota>();
        }
    
        public long idEstadoDeCuenta { get; set; }
        public decimal porcentajeDescuento { get; set; }
        public decimal mtoDescuento { get; set; }
        public decimal mtoSubtotal { get; set; }
        public decimal debe { get; set; }
        public decimal haber { get; set; }
        public decimal saldo { get; set; }
        public decimal inicial { get; set; }
        public decimal porcentajeInteres { get; set; }
        public decimal mtoInteres { get; set; }
        public System.DateTime fecRegistro { get; set; }
        public Nullable<System.DateTime> fecModificacion { get; set; }
        public long idUsuario { get; set; }
        public Nullable<long> idUsuarioModificar { get; set; }
        public long idCita { get; set; }
    
        public virtual CLlt05_cita CLlt05_cita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TNSt03_cuota> TNSt03_cuota { get; set; }
    }
}
