//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_BusinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNSt02_comprobanteEmitidoDtl
    {
        public long idComprobanteEmitidoDtl { get; set; }
        public decimal precio { get; set; }
        public decimal cantidad { get; set; }
        public long idComprobanteEmitido { get; set; }
        public long idCitaDtl { get; set; }
    
        public virtual CLlt06_citaDtl CLlt06_citaDtl { get; set; }
        public virtual TNSt01_comprobanteEmitido TNSt01_comprobanteEmitido { get; set; }
    }
}
