//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_BusinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNSt06_medioDePagoDtl
    {
        public long idMedioDePagoDtl { get; set; }
        public decimal fecRegistro { get; set; }
        public Nullable<System.DateTime> fecModificacion { get; set; }
        public Nullable<System.DateTime> fecEliminacion { get; set; }
        public decimal mtoMedioDePago { get; set; }
        public Nullable<decimal> tipoDeCambio { get; set; }
        public bool activo { get; set; }
        public long idUsuario { get; set; }
        public Nullable<long> idUsuarioModificar { get; set; }
        public Nullable<long> idUsuarioEliminar { get; set; }
        public long idComprobanteEmitido { get; set; }
        public short idMedioDePago { get; set; }
    
        public virtual MSTt01_medioDePago MSTt01_medioDePago { get; set; }
        public virtual TNSt01_comprobanteEmitido TNSt01_comprobanteEmitido { get; set; }
    }
}
